<?php

namespace App;

use App\Scopes\SellerScope;

class Seller extends User
{

    protected $table = 'users';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new SellerScope);
    }

    // Un vendedor tiene muchos productos
    public function products(){
        return $this->hasMany(Product::class);
    }
}
