<?php

namespace App;

use App\Scopes\SellerScope;
use App\Transformers\SellerTransformer;


class Seller extends User
{

    protected $table = 'users';

    // Especificando la transformacion
    public $transformer = SellerTransformer::class;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new SellerScope);
    }

    // Un vendedor tiene muchos productos
    public function products(){
        return $this->hasMany(Product::class);
    }
}
